import type { Metadata } from "next";
<<<<<<< HEAD
import { Karla } from "next/font/google";
import "./globals.css";
import { satoshi } from "../fonts/font";

const geistKarla = Karla({
  variable: "--font-geist-karla",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
>>>>>>> 52f6f89 (Initial commit from Create Next App)
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "SnapCast",
  description: "A Screen Sharing App",
  icons: {
    icon: "/assets/icons/logo.svg",
  },
};

export default function Layout({
=======
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
>>>>>>> 52f6f89 (Initial commit from Create Next App)
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistKarla.variable} ${satoshi.variable} font-karla antialiased`}
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>>>>>>> 52f6f89 (Initial commit from Create Next App)
      >
        {children}
      </body>
    </html>
  );
}
